### PR TITLE
setup the project

### PR DESCRIPTION
**Pull request by alisonpchase**

### CODE REVIEW

**Comment by cisaacstern** [comment]
@alisonpchase, I just set up automated testing with Github. You will see that we now have a banner that says **All checks have passed** and if you click **Show all checks** you will see something like
Screen Shot 2021-11-16 at 5 31 23 PM

This means that the `tests/test_pigments.py` tests from the latest commit of our PR have been run twice, once with Python version 3.8 and once with Python version 3.9, and all tests passed for both cases. If you click the **Details** link circled in red above you can see some terminal output from these test runs.

From now on, all commits pushed to our `dev` branch will have all `tests` present in the latest commit run automatically. (So as we update and add new tests, they will be run as well.)

From your standpoint, this means two things:

1. Remember to `git fetch origin dev` and `git merge origin/dev` at the start of your next working session so your local branch is synced with these changes.
2. If you add other imports (such as `numpy`), they will need to be added to the project dependencies in `setup.cfg` here: 

https://github.com/alisonpchase/pigments-from-rrs/blob/6105fac96e30054e26c19e7ead8595889e46e95a/setup.cfg#L9-L10

This is how the test automation knows what dependencies the project requires. If we try to import something in `spectra.py`, for example, that is not listed as a depenedency in `setup.cfg`, the tests might pass on our local environment (if we installed the dependency there), but the Github automation tests will fail.

Let me know if you have any questions! Super psyched about this because we now have great visibility into the test suite on our PR.

**Comment by alisonpchase** [comment]
Awesome, thanks @cisaacstern ! okay, I am trying to work on the code, starting with importing my data. I am stuck on step 1 of importing my .csv file...I'm trying to do this:
# Read and open data file
    df = pd.read_csv(r'/Users/alisonchase/Dropbox/PACE_ST/Rrs_test.csv')
    print (df)

but the code gives an error at the very start where I have:
import pandas as pd

and it says: 
Import "pandas" could not be resolved from source
Pylance(reportMissingModuleSource)

I tried installing pandas and making sure I had the right environment activated...help...
thanks :)

**Comment by cisaacstern** [comment]
@alisonpchase, great that you're getting into it! One meta tip first. When you're writing code on a GitHub comment thread, you can enclose it in triple backticks and note the language name to get syntax highlight, which improves readability.

So for example, inputing

<pre>
```python
import pandas as pd
```
</pre>

in the **Write** tab of the comment, renders to

```python
import pandas as pd
```
🎉 

For errors, generally you can just enclose them in backticks without syntax highlighting, so

<pre>
```
Import "pandas" could not be resolved from source
Pylance(reportMissingModuleSource)
```
</pre>

becomes

```
Import "pandas" could not be resolved from source
Pylance(reportMissingModuleSource)
```

I'll respond to your actual question in a separate comment to make it easier to separate these concerns 😄

**Comment by cisaacstern** [comment]
(Ok, one more meta comment, I'm using `>` at the start of the line to make a blockquote.)

> but the code gives an error at the very start where I have:
import pandas as pd

> and it says:
Import "pandas" could not be resolved from source
Pylance(reportMissingModuleSource)

Right! So my first question is within your project environment, if you run `pip show pandas`, does it reflect that pandas is actually installed? For example, when I run

```shell
➜  pip show pandas
```
in an environment with pandas installed, I get

```
Name: pandas
Version: 1.3.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /Users/charlesstern/miniconda3/envs/xstac/lib/python3.8/site-packages
Requires: numpy, pytz, python-dateutil
Required-by: xstac, xarray, cf-xarray
```

**Comment by alisonpchase** [comment]
@cisaacstern thank you for the tips on how to write the comments here!

okay, yes - when I run ```pip install pandas``` I get a similar printout to what yours shows
```
Name: pandas
Version: 1.3.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /Users/alisonchase/miniconda3/envs/pigments/lib/python3.8/site-packages
Requires: python-dateutil, pytz, numpy
Required-by: 
```

**Comment by cisaacstern** [comment]
Ok gotcha so I just realized this is an issue where VS Code doesn't realize what environment you want to use for your editor session. You can change the environment VS Code is using like this:

https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

Haha, I actually had been having this same issue for a few days and your question finally prompted me to figure out how to solve it. The reason I could have it for a few days without fixing it is that this is not really a question of a code itself but rather how VS Code is trying to help you. When the correct environment is selected for VS Code, it can tell you when there are actually uninstalled packages.

If you were to have run this code, `import pandas as pd` would have worked fine.

**Comment by cisaacstern** [comment]
> You can change the environment VS Code is using like this: https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

To clarify, from the dropdown of environments, your `pigments` project environment should be one of the options, and if you select it, the warning should go away.

**Comment by alisonpchase** [comment]
Ok, great - I had tried that and tried closing and opening the code but that didn't fix it, but I just quit vscode complete and reopened the code and now the error is gone. Thank you!!

**Comment by cisaacstern** [comment]
@alisonpchase, I recommend we merge this PR. In its current state, it accomplishes a lot which is already of great benefit to the project, including

- making the project minimally installable with a `pyproject.toml` and `setup.py` etc
- adding a `tests` directory
- implementing automated testing on GitHub via the `.github/workflows/main.yaml` configuration file

I suggest any next steps we take on `pigments-from-rrs` begin with a fresh PR with its own narrowly-focused scope.

If you agree, go ahead and click the green **Merge pull request** below this comment; if not let me know and I'll be happy to discuss further.

**Comment by alisonpchase** [comment]
@cisaacstern great, done. Now should I delete the ```dev``` branch? Or will we keep using the name for new ones?

**Comment by cisaacstern** [comment]
@alisonpchase, awesome. Yes, you can delete `dev`. Best practice is to start a new branch for each PR you are working on. So for example if you end up working on a "Reading CSVs with Pandas" PR, you could make a new branch `read-csv` for that.

**Pull request merged**
